# Rad sa matricama

Kao što smo videli, višedimenzioni nizovi predstavljaju osnovnu strukturu podataka biblioteke `numpy`. Paket `numpy.linalg` specifično podržava razne algebarske funkcionalnosti u radu sa matricama, među kojima su nalaženje determinante matrice, njenog inverza, sopstvenih vektora i sopstvenih vrednosti, normi, uslovljenosti i drugih.  

In [1]:
import numpy as np
from numpy import linalg as LA

Za demonstraciju funkcija `numpy.linalg` paketa, kreiraćemo kvadratnu matricu 
$A = \begin{bmatrix}
    1 & 2 & 4 \\
    -5 & 7 & 2 \\
    5 & 1 & 9
\end{bmatrix}$.

In [2]:
A = np.array([
    [1, 2, 4],
    [-5, 7, 2],
    [5, 1, 9]
])

In [3]:
A

array([[ 1,  2,  4],
       [-5,  7,  2],
       [ 5,  1,  9]])

`Determinanta` matrice se može definisati rekurzivno. Tako za matrice reda $2 \times 2$, $3 \times 3$ i $4 \times 4$, važi 

* $\begin{vmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{vmatrix} = a_{11}a_{22}-a_{12}a_{21},$
* $\begin{vmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{vmatrix} = a_{11}\begin{vmatrix}a_{22}&a_{23}\\a_{32}&a_{33}\end{vmatrix} - a_{12}\begin{vmatrix}a_{21}&a_{23}\\a_{31}&a_{33}\end{vmatrix} + a_{13}\begin{vmatrix}a_{21}&a_{22}\\a_{31}&a_{32}\end{vmatrix},$ 
* $\begin{vmatrix}a_{11}&a_{12}&a_{13}&a_{14}\\a_{21}&a_{22}&a_{23}&a_{24}\\a_{31}&a_{32}&a_{33}&a_{34}\\a_{41}&a_{42}&a_{43}&a_{44}\end{vmatrix} = a_{11} \begin{vmatrix}a_{22}&a_{23}&a_{24}\\a_{32}&a_{33}&a_{34}\\a_{42}&a_{43}&a_{44}\end{vmatrix} - a_{12} \begin{vmatrix}a_{21}&a_{23}&a_{24}\\a_{31}&a_{33}&a_{34}\\a_{41}&a_{43}&a_{44}\end{vmatrix} + a_{13}
\begin{vmatrix}a_{21}&a_{22}&a_{24}\\a_{31}&a_{32}&a_{34}\\a_{41}&a_{42}&a_{44}\end{vmatrix} - a_{14} \begin{vmatrix}a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\a_{41}&a_{42}&a_{43}\end{vmatrix}.$

Svaki sabirak u izrazu za izračunavanje determinante predstavlja proizvod jednog elementa matrice i determinante matrice koja se dobija od polazne uklanjanjem reda i kolone kojima pripada taj element. Za razlaganje se mogu odabrati svi elementi proizvoljne vrste ili kolone. U našem slučaju su uzeti elementi prve vrste. Svaki drugi sabirak u izrazu treba da bude pomnožen sa $-1$. 

Ova definicija se lako može uopštiti i na matrice većeg reda.

Za uočenu matricu $A$, vrednost determinante se može interpretirati kao mera skaliranja i promene orijentacije preslikavanja određenog matricom $A$.

Za računanje determinante matrice koristimo funkciju `det`:

In [4]:
LA.det(A)

10.999999999999972

Ukoliko je determinanta kvadratne matrice $A$ različita od nule, postoji njen `inverz` tj. matrica $A^{-1}$ za koji važi $AA^{-1}=I$, gde je $I$ jedinična matrica.

Za računanje inverza matrice koristimo funkciju `inv`:

In [5]:
LA.inv(A)

array([[ 5.54545455, -1.27272727, -2.18181818],
       [ 5.        , -1.        , -2.        ],
       [-3.63636364,  0.81818182,  1.54545455]])

Za matrice čija je determinanta jednaka nuli kažemo da su `singularne` matrice.

Ako za neki realan vektor $x$ važi $Ax = \lambda x$, gde je $\lambda$ skalar, vektor $x$ se naziva `sopstveni vektor`, a $\lambda$ `sopstvena vrednost` matrice $A$. 

<img src='assets/eigenvectors.gif'>

Intuitivno, sopstveni vektori su vektori koji u matričnim transformacijama ne menjaju svoj pravac. Sopstvene vrednosti reflektuju promenu njihovog intenziteta i smera. 

U opštem slučaju sopstvene vrednosti se dobijaju kao nule jednačine $det(A-\lambda I)=0$, takozvanog karakterističnog polinoma. Nešto kasnije na kursu ćemo upoznati metode stepenovanja i iscrpljivanja za dobijanje sopstvenih vrednosti. Na nivou biblioteke nam je na raspolaganju funkcija `eig` koja izračunava sopstvene vrednosti i normirane sopstvene vektore. 

In [6]:
values, vectors = LA.eig(A)

In [7]:
values

array([ 0.17157288,  5.82842712, 11.        ])

In [8]:
vectors

array([[ 6.57393413e-01, -6.10635274e-02,  3.71390676e-01],
       [ 6.10673901e-01, -9.20292562e-01,  7.22840190e-16],
       [-4.41487584e-01,  3.86436083e-01,  9.28476691e-01]])

**Norma** matrice $A$ je nenegativan broj $||A||$ za koji važi: 

* $||A|| \ge 0$
* $||A|| = 0$ ako i samo ako je $A = 0$,
* $||kA|| = |k|\cdot||A||$, za $k$ koje pripada prostoru skalara
* $||A+B||\le||A||+||B||$,

Među najpoznatijim normama su matrična `1-norma`, matrična `2-norma`, matrična $\infty$`-norma` i `Frobeniusova` norma.

* **Matrična 1-norma** predstavlja maksimalni zbir sume apsolutnih vrednosti elemenata u svakoj koloni i definisana je sa $||A||_1 = \max_j \sum_i |a_{ij}|$.

* **Matrična 2-norma** je jednaka korenu najveće sopstvene vrednosti matrice $A^TA$ i definisana je sa $||A||_2 = \sqrt{\lambda_{max} (A^TA)}$. U slučaju kompleksne matrice, umesto transponovane, koristi se [konjugovana transponovana matrica](http://mathworld.wolfram.com/ConjugateTranspose.html).

* **Frobeniusova norma** predstavlja koren sume apsolutnih vrednosti svih elemenata matrice i definisana je sa $||A||_F = \sqrt{\sum_i \sum_j |a_{ij}|^2}$. Važi $||A||_2 \le ||A||_F \le \sqrt{r} \cdot ||A||_2$, gde je $r$ rang matrice $A$.

* **Matrična $\infty$-norma** predstavlja maksimalni zbir sume apsolutnih vrednosti elemenata u svakom redu i definisana je sa $||A||_{\infty} = \max_i \sum_j |a_{ij}|$.

Za računanje norme koristićemo funkciju `norm`, a njenim parametrom `ord` naglašavaćemo o kojoj normi je reč.

In [9]:
LA.norm(A, ord=1)

15.0

In [10]:
LA.norm(A, ord=np.inf)

15.0

In [11]:
LA.norm(A, ord='fro')

14.352700094407323

U prostoru konačne dimenzije ($R^n$ ili $R^{nxm}$ su slučajevi koje razmatramo) sve norme su međusobno ekvivalentne. To znači da za dve norme $\|\|_{n1}$ i $\|\|_{n2}$ postoje pozitivne realne konstante $c_1$ i $c_2$ takve da je $c_1\cdot\|x\|_{n1}\leq \|x\|_{n2} \leq c_2\cdot\|x\|_{n1}$  

U opštem slučaju, norma matrice **indukovana** normom vektora $||\cdot||_a$ se definiše kao $||A||_a = max_{||x||_a=1}||Ax||_a = max_{||x||_a \neq 0} \frac{||Ax||_a}{||x||_a}$.

<img src='assets/induced_matrix_norm.png'>


Intuitivno ovako definisanu normu matrice možemo interpretirati kao vrednost radijusa kruga tj. hipersfere koja sadrži sva preslikavanja polaznih jediničnih vektora. Na ovaj način se steče predstava i o gornjim ograničenjima očekivanih transformacija polaznih vektora. 

`Kondicioni broj` $\kappa(A)$ kvadratne invertibilne matrice $A$ je numerička vrednost koja se definiše sa $\kappa(A) = ||A||\cdot||A^{-1}||$. Ukoliko matrica $A$ nije invirtibilna, tada je $\kappa(A) = \infty$. 

Za računanje kondicionog broja koristićemo funkciju `cond`.

In [12]:
LA.cond(A)

102.39895228883073

In [15]:
LA.norm(A, ord=2) * LA.norm(LA.inv(A), ord=2)

102.39895228883104

Kondicioni broj zavisi od vrste norme matrice. Podrazumevano se koristi matrična 2-norma.

Praktično, kondicioni broj ukazuje na numeričku stabilnost sistema u kojima matrica figuriše. Za sistem jednačina $Ax=b$, vrednost $\kappa(A)$ određuje promenu vrednosti vektora $x$ u zavisnosti od promene vrednosti vektora $b$. Ukoliko je vrednost $\kappa(A)$ velika, tada i male promene vrednosti vektora $b$ utiču da se vrednost vektora $x$ dosta promeni. Ako je vrednost kondicionog broja mala, onda promena vektora $x$ neće biti naročito velika.

Ilustrujmo to primerom 
$\begin{bmatrix}
    1 & 2 \\
    2 & 3.999
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2
\end{bmatrix}
=
\begin{bmatrix}
4 \\
7.999
\end{bmatrix}
$

In [16]:
A = np.array([
    [1, 2], 
    [2, 3.999]
])

In [17]:
b = np.array([4, 7.999]).T

In [18]:
x = LA.inv(A).dot(b)

In [19]:
x

array([2., 1.])

In [20]:
A1 = A.copy()
b1 = b.copy()
b1[0] += 0.001
b1[1] -= 0.001

In [21]:
x1 = LA.inv(A1).dot(b1)

In [22]:
x1

array([-3.999,  4.   ])

In [23]:
A2 = A.copy()
A2[0, 0] += 0.001
A2[0, 1] += 0.001
A2[1, 0] += 0.001
A2[1, 1] -= 0.001

b2 = b.copy()

In [24]:
x2 = LA.inv(A2).dot(b2)

In [25]:
x2

array([ 6.98901648, -1.49725412])

In [26]:
LA.cond(A)

24992.000960058016

Poznata klasa loše uslovljenih matrica su **Hilbertove matrice**. Hilbertova matrica reda $n$ je matrica čiji su elementi oblika $H_{i, j} = \frac{1}{i+j-1}$ za i, j = 1, 2, 3, ...  Na primer, Hilbertova matrice reda 3 je $
\begin{bmatrix}
1 & \frac{1}{2} & \frac{1}{3} \\
\frac{1}{2} & \frac{1}{3} & \frac{1}{4} \\
\frac{1}{3} & \frac{1}{4} & \frac{1}{5} \\
\end{bmatrix}
$.

Sledeća funkcija konstruiše Hilbertovu matricu reda $n$.

In [27]:
def hilbert_matrix(n):
    H = np.zeros((n, n))

    for i in range(0, n):
        for j in range(0, n):
            H[i, j] = 1 / ((i + 1) + (j + 1) - 1)
            
    return H

In [28]:
hilbert_matrix(3)

array([[1.        , 0.5       , 0.33333333],
       [0.5       , 0.33333333, 0.25      ],
       [0.33333333, 0.25      , 0.2       ]])

Neka dalje funkcija `b_values` za date parametre $n$ i $\sigma$ generiše vektor $b$ čiji su elementi određeni sa $$b_i = \sum_{j=1}^{j=n}{\frac{1}{i+j-1}}+\sigma R(i)$$ u kojem $R(i)$ predstavlja slučajan broj iz intervala $[-1, 1]$.

In [29]:
def b_values(n, sigma):
    b = np.zeros(n)

    for i in range(0, n):
        b[i] = np.sum([1 / ((i + 1) + (j + 1) - 1) for j in range(0, n)]) + sigma*np.random.uniform(-1, 1)
        
    return b

In [30]:
b_values(3, 10**-2)

array([1.82597197, 1.07660817, 0.78768357])

Napisaćemo i funkciju `solve_hilbert_system` koja rešava sistem jednačina $Hx=b$ za zadate vrednosti parametara $n$ i $\sigma$ u kojem je $H$ Hilbertova matrica reda $n$, a vektor vrednosti $b$ vektor dobijen uz pomoć funkcije `b_values`.

In [31]:
def solve_hilbert_system(n, sigma):
    H = hilbert_matrix(n)
    b = b_values(n, sigma)
    
    return LA.inv(H).dot(b)

Koristeći napisanu funkciju rešićemo sistem jednačina $Hx=b$ za $n=10$ i $\sigma=10^{-14}$, a potom i za vrednosti $n=10$ i $\sigma=10^{-5}$.

In [32]:
n = 10 
sigma_1 = 10**-14
sigma_2 = 10**-5

In [33]:
solve_hilbert_system(n, sigma_1)

array([1.00001397, 0.99928796, 1.00097847, 1.00112915, 0.99047852,
       1.02734375, 0.95507812, 1.04248047, 0.97802734, 1.00469971])

In [34]:
solve_hilbert_system(n, sigma_2)

array([-1.01744071e+02,  8.83988417e+03, -1.87735460e+05,  1.70347964e+06,
       -8.11447632e+06,  2.22852845e+07, -3.65374596e+07,  3.52903964e+07,
       -1.85196010e+07,  4.07145468e+06])

In [35]:
H_10 = hilbert_matrix(n)
LA.cond(H_10)

16025028168113.176